name: publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{github.ref_name}}
      REGISTRY: quay.io/kubevirt
    steps:
      - uses: actions/checkout@v2
      - uses: arnested/go-version-action@v1
        id: go-versions
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-versions.outputs.minimal }}
      - name: Logging to quay.io
        run: 
          docker login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }} quay.io
      - name: Build and push image
        run: make image push
      - name: Tag manifests
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sed -i "s/main/${{github.ref_name}}/" $(git grep -l :main config/)
          tar -cvzf kustomize.tar.gz config
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: kustomize.tar.gz
